# Generated by Django 5.2.4 on 2025-07-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sweet',
        ),
    ]
